### ISSUE TITLE
PCM click fix causes violation of 48 MHz constraint

### ISSUE THREAD

**Issue by edenfrosst** [Spritetm/hadbadge2019_fpgasoc#122]
With the changes in #118, making the `soc/` errors with:

    ERROR: Max frequency for clock                  '$glbnet$clk48m': 46.22 MHz (FAIL at 48.00 MHz)

**Comment by Spritetm** [comment]
Could depend on your see, can you change soc/Makefile to try a different one?

**Comment by edenfrosst** [comment]
Tried and found a value that works. Should I make a PR for it?

**Comment by Spritetm** [comment]
You can if you want to, but there may not be much use, as the seed effects are consistent on one computer/install/... only. For instance, the current seed works for me. (pass at 51.79MHz)

**Comment by edenfrosst** [comment]
Ah, I see. Though it might be deterministic. Well, that makes this issue irrelevant. Might make a PR making the seed value more clear for the FPGA docs.
