### ISSUE TITLE
frame buffer problem causes horizontal line problems at specific y positions

### ISSUE THREAD

**Issue by mattvenn** [Spritetm/hadbadge2019_fpgasoc#143]
**Expected behaviour**

drawing a horizontal line by setting pixels in the frame buffer should result in a single pixel wide line on the display.

**Resulting behaviour**

- Drawing a line at y = 2 works as expected
- Drawing a line at y = 3 results in 2 short lines with a pixel space between them
- Drawing a line at y = 4 results in 2 px wide line in some places
- Drawing a line at y = 5 works as expected
![lineerror](https://user-images.githubusercontent.com/634220/69808471-d660b100-11e7-11ea-8818-3f6bf913358a.png)

**To reproduce**

- Clone https://github.com/mattvenn/had-badge-draw-app/tree/linetest
- make and copy to badge
- button up draws a 200 pix horizontal line at y = 2
- button right draws at y = 3 (with glitches as described above)
- button down draws at y = 4 (with glitches as above)
- button left draws at y = 5 which works as expected

**Comment by shaos** [comment]
Based on my experience it looks like DMA draws every ODD line of framebuffer twice (and EVEN lines are completely ignored). This is happening with FB only - tiles and sprites look high-res...

**Comment by shaos** [comment]
It sounds funny, but I think I've just fixed EVEN lines issue :)

Example with lines from Matt now draw "ghost" short line in case of y=4, but in all other cases lines look correct (I made background blue to count pixels):
![badge](https://github.com/Spritetm/hadbadge2019_fpgasoc/assets/236968/047508c3-889f-45a3-9ecf-df415ab18721)

**Comment by shaos** [comment]
This is my pull-request:
https://github.com/Spritetm/hadbadge2019_fpgasoc/pull/155

**Comment by Spritetm** [comment]
Seems fixed by Shaos' PR.
