### ISSUE TITLE
Need hardware timer for C code

### ISSUE THREAD

**Issue by szczys** [Spritetm/hadbadge2019_fpgasoc#43]
Apps written in C need access to some reliable hardware timer to implement non-blocking delays.

- Could be a 32-bit register that increments every millisecond
- @Spritetm mentioned it might be possible to add an indication of the 60 Hz vblank signal

**Comment by smunaut** [comment]
The riscv architecture includes provision for hardware counters, it's as simple as enabling them in the picorv32 CPU.

Having an interrupt on vblank would probably be useful for games in any case ...

**Comment by Spritetm** [comment]
There's a vbl counter now that is pretty useful for e.g. waiting x frames, or waiting until you can write data for the next frame. See ipl main.c for an example.
