### ISSUE TITLE
Add Badgetris! as submodule

### ISSUE THREAD

**Issue by szczys** [Spritetm/hadbadge2019_fpgasoc#48]
I have a stable version of this ready. Is adding this as a submodule the best way to include it in the project?

```git submodule add https://github.com/szczys/badgetris-2019supercon.git app-badgetris```

## Known issues:

* Background image has some flicker in the lower third of it. I'm unsure if this is my code an issue with the IPL.

**Comment by Spritetm** [comment]
Sure! Note that the way submodules work is that they're pinned to a certain commit in your badgetris repo; if you do any upgrades on badgetris, you also need to add a push request to update the module here.

Will add the submodule as soon as I'm done hacking here.

**Comment by Spritetm** [comment]
Added.
