### ISSUE TITLE
Frame counter in GFX_REGS ?

### ISSUE THREAD

**Issue by alanvgreen** [Spritetm/hadbadge2019_fpgasoc#50]
What do you reckon about adding a couple of GFX registers to count these things?

(a) total frames since reset,
(b) lines since start of frame.

Being able to see the current frame number would be useful for apps doing animation - including the IPL menu. Knowing the number of lines since start of frame might help someone avoid tearing issues in certain complicated scenarios.

I'm happy to send a pull request - just wanted to make sure this kind of thing wasn't against the early-90's aesthetic :)

**Comment by Spritetm** [comment]
They're already implemented -  GFX_VBLCTR_REG counts the vbls since start (and thus the amount of frames), GFX_VIDPOS_REG shows you the current x and y position the renderer is working on.
