### ISSUE TITLE
home for docs: Windows Ten Minute Setup Guide

### ISSUE THREAD

**Issue by alanvgreen** [Spritetm/hadbadge2019_fpgasoc#70]
I wrote a quick setup guide for Windows. 

https://gist.github.com/alanvgreen/daff0777002aa9f31e79b3e47bad6e71

Where's the right place for this? I don't think there's a straight forward way to send a pull request for the project's wiki pages.

**Comment by Spritetm** [comment]
Hm, I'm not that much a fan of the wiki in general... it seemed useful to do a ToDo, but I think issues are better for that. Perhaps we need to add a doc/ folder to the main Git repo and dump manuals in there?

**Comment by alanvgreen** [comment]
Works for me!

**Comment by Spritetm** [comment]
Merged, thanks!
